copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst1.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst2.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst3.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst4.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst5.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst6.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst7.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst8.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst9.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst10.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst11.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst12.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst13.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst14.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst15.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst16.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst17.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst18.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst19.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst20.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst21.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst22.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst23.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst24.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst25.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst26.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst27.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst28.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst29.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst30.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst31.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst32.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst33.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst34.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst35.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst36.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst37.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst38.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst39.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst40.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst41.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst42.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst43.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst44.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst45.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst46.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst47.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst48.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst49.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst50.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst51.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst52.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst53.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst54.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst55.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst56.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst57.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst58.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst59.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst60.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst61.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst62.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst63.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst64.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst65.p
copy d:\medistar\inst\inst0.p       d:\medistar\inst\inst66.p

copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox1.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox2.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox3.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox4.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox5.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox6.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox7.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox8.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox9.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox10.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox11.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox12.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox13.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox14.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox15.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox16.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox17.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox18.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox19.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox20.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox21.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox22.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox23.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox24.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox25.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox26.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox27.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox28.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox29.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox30.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox31.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox32.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox33.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox34.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox35.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox36.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox37.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox38.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox39.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox40.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox41.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox42.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox43.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox44.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox45.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox46.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox47.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox48.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox49.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox50.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox51.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox52.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox53.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox54.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox55.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox56.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox57.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox58.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox59.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox60.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox61.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox62.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox63.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox64.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox65.xml
copy d:\medistar\inst\toolbox0.xml      d:\medistar\inst\toolbox66.xml

copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-1.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-2.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-3.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-4.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-5.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-6.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-7.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-8.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-9.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-10.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-11.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-12.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-13.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-14.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-15.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-16.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-17.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-18.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-19.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-20.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-21.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-22.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-23.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-24.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-25.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-26.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-27.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-28.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-29.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-30.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-31.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-32.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-33.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-34.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-35.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-36.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-37.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-38.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-39.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-40.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-41.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-42.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-43.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-44.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-45.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-46.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-47.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-48.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-49.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-50.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-51.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-52.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-53.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-54.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-55.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-56.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-57.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-58.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-59.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-60.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-61.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-62.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-63.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-64.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-65.ini
copy d:\medistar\inst\medistar-task-0.ini      d:\medistar\inst\medistar-task-66.ini

write-output "                                "
write-output "                             OK!"
write-output "                                "
pause